# Generated by Django 3.0.5 on 2020-04-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='standerd',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], default='1st', max_length=20),
        ),
    ]
