# Generated by Django 3.0 on 2020-04-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200418_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='standerd',
        ),
        migrations.AddField(
            model_name='student',
            name='standard',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('Diploma', 'Diploma'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('PhD', 'PhD'), ('Others', 'Others')], default='1st', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
