# Generated by Django 3.0 on 2020-04-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200419_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='standard',
            new_name='standerd',
        ),
    ]
