# Generated by Django 3.0 on 2020-04-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200419_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='standerd',
            new_name='standard',
        ),
    ]
