# Generated by Django 3.0 on 2020-04-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200419_2245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
